troubleshooting

diff --git a/.github/workflows/publish-to-pypi.yml b/.github/workflows/publish-to-pypi.yml
--- a/.github/workflows/publish-to-pypi.yml
+++ b/.github/workflows/publish-to-pypi.yml
@@ -70,6 +70,11 @@ jobs:
           ./dist/*.whl
 
     # Create a GitHub Release if it doesn't exist
+    - name: Debug directory structure
+      run: |
+        pwd
+        find .
+        cat ./PythonAdvancedTyping/setup.py || echo "setup.py not found!"
     - name: Get version from package
       id: get_version
       run: |
